from .requests.dinner.dinner_requests import CreateSpecialDinnerRequest, AddDinnerParticipantRequest, AddDinnerGuestRequest
from .requests.guests.guest_requests import CreateGuestRequest, UpdateGuestAllergiesRequest
from .requests.tenants.tenants_requests import UpdateTenantAllergiesRequest, CreateTenantRequest, DeactivateTenantRequest, UpdateTenantPreferencesRequest, UpdateTenantRequest